### ISSUE TITLE
Question about inference 

### ISSUE THREAD

**Issue by leohsuofnthu** [yangheng95/PyABSA#47] opened 2021-07-26 15:56 UTC
Hi, thanks for the nice work. Recently I try to use the multilingual pretrained model for inference. I found that if the model predicts both of 2 consecutive words as (B-ASP). There will be a 'empty separator' error while inferencing. Is there any advice for avoiding this situation? Thanks again !

![image](https://user-images.githubusercontent.com/42263429/127020360-327f1d51-e806-44a8-a971-8edfe6ea7c82.png)
![image](https://user-images.githubusercontent.com/42263429/127020399-c9a2dafa-583c-4035-8de6-128e463ac477.png)

**Comment by yangheng95** [comment] 2021-07-26 16:29
Thank you for your feedback! We will fix it as soon as possible. 

FYI, the provided checkpoints are for research only and not trained with sufficient resources. Fit the model on your datasets will bring performance improvement.

**Comment by yangheng95** [comment] 2021-07-26 16:55
> Hi, thanks for the nice work. Recently I try to use the multilingual pretrained model for inference. I found that if the model predicts both of 2 consecutive words as (B-ASP). There will be a 'empty separator' error while inferencing. Is there any advice for avoiding this situation? Thanks again !
> 
> ![image](https://user-images.githubusercontent.com/42263429/127020360-327f1d51-e806-44a8-a971-8edfe6ea7c82.png)
> ![image](https://user-images.githubusercontent.com/42263429/127020399-c9a2dafa-583c-4035-8de6-128e463ac477.png)

I review the code, as a temp solution, please alter this if-clasuse https://github.com/yangheng95/PyABSA/blob/41a067aec58b067058c1998eba33b2d9908f4989/pyabsa/tasks/atepc/prediction/aspect_extractor.py#L233
into 
``` 
if 'B-ASP' == pred_iobs[iob_idx] and 'B-ASP' in pred_iobs[iob_idx + 1] \
   or 'B-ASP' == pred_iobs[iob_idx] and 'ASP' not in pred_iobs[iob_idx + 1] \
   or 'I-ASP' == pred_iobs[iob_idx] and 'ASP' not in pred_iobs[iob_idx + 1]:
```

I will be appreciated if you told me the feasibility of this solution. If it works OK, I will merge into the package, many thanks!

**Comment by leohsuofnthu** [comment] 2021-07-26 18:08
Hi, Thanks for the quick response. I bump into another situation as below. Hope this helpful for you.
![image](https://user-images.githubusercontent.com/42263429/127056947-bee3e382-7798-4979-bc50-ca7420b673ef.png)

**Comment by yangheng95** [comment] 2021-07-27 01:31
Hi, thanks for your message. However the information from this screen is limited. Can you show me the whole error stacktrace and the example text?

**Comment by yangheng95** [comment] 2021-07-27 02:01
> Hi, Thanks for the quick response. I bump into another situation as below. Hope this helpful for you.
> ![image](https://user-images.githubusercontent.com/42263429/127056947-bee3e382-7798-4979-bc50-ca7420b673ef.png)

Hi, 
Using following if-caulse is more clear and may solve this preoblem.
                    if 'B-ASP' == pred_iobs[iob_idx] and 'B-ASP' == pred_iobs[iob_idx + 1] \
                            or 'I-ASP' == pred_iobs[iob_idx] and 'B-ASP' == pred_iobs[iob_idx + 1]:

**Comment by leohsuofnthu** [comment] 2021-07-27 16:08
Hi,
Thanks, the code works, the new problem is that it ll combine distinct aspects as below:
![image](https://user-images.githubusercontent.com/42263429/127188757-03f60c6a-f0a2-4cbc-b88d-456bb5b7d336.png)

**Comment by yangheng95** [comment] 2021-07-27 16:32
Sorry for the buggy repair, I should release the repaire after full test of the code  given a cuda device and enough cases. I will check and update again.

Since I cannot run full test then, I suggest you to change the if-clause again, as following:
```
    if pred_iobs[iob_idx].endswith('ASP') and not pred_iobs[iob_idx + 1].endswith('ASP'):
```

**Comment by leohsuofnthu** [comment] 2021-07-27 16:40
No worry, it is great to help with this useful repository !

**Comment by yangheng95** [comment] 2021-07-27 16:48
I will be appreciated if you futher collect the bad cases and pass them to me

**Comment by leohsuofnthu** [comment] 2021-07-27 16:57
No problem, Here is the error for the newest modification
![image](https://user-images.githubusercontent.com/42263429/127196139-338981b0-bdd6-4e29-8ed5-12cf0e61c56e.png)

**Comment by yangheng95** [comment] 2021-07-27 17:11
> No problem, Here is the error for the newest modification
> ![image](https://user-images.githubusercontent.com/42263429/127196139-338981b0-bdd6-4e29-8ed5-12cf0e61c56e.png)

I mean could you paste the example texts to me to reproduce your errors?

**Comment by leohsuofnthu** [comment] 2021-07-27 17:16
Here is the text:

'I am extremely disappointed and frustrated with the Granite Club programming since you seem to think the only preschoolers or parents that would be interested in participating are those who are stay at home parents or have at home help to bring children to weekday programming.'

and the model:
`model_path = ATEPCTrainedModelManager.get_checkpoint(checkpoint_name='english')`

**Comment by yangheng95** [comment] 2021-07-28 01:53
if pred_iobs[iob_idx].endswith('ASP') and not pred_iobs[iob_idx + 1].endswith('I-ASP'):

**Comment by yangheng95** [comment] 2021-07-28 01:55
I test this example, however, I develop this package based on several cases and dont have enough example texts. If any error occurs please let me know, many thanks!

**Comment by leohsuofnthu** [comment] 2021-07-29 13:39
Thank you ! I end up inferencing with version 0.8.7.9, and it works well for now :)

**Comment by yangheng95** [comment] 2021-07-29 14:37
> Thank you ! I end up inferencing with version 0.8.7.9, and it works well for now :)

I will close this issue, but feel free to contact me if you have more advice or report.

**Closed as completed** 2021-07-29 14:40 UTC
Labels: bug
